n = int(input())
print(n)
x, n = divmod(n, 100)
print(x, "nota(s) de R$ 100,00")
x, n = divmod(n, 50)
print(x, "nota(s) de R$ 50,00")
x, n = divmod(n, 20)
print(x, "nota(s) de R$ 20,00")
x, n = divmod(n, 10)
print(x, "nota(s) de R$ 10,00")
x, n = divmod(n, 5)
print(x, "nota(s) de R$ 5,00")
x, n = divmod(n, 2)
print(x, "nota(s) de R$ 2,00")
x, n = divmod(n, 1)
print(x, "nota(s) de R$ 1,00")
